version: '3.8'

services:
  web:
    build: ./services/web
    command: "python manage.py run -h 0.0.0.0 -p ${PORT}"
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  postgres_data:

    